# SPDX-License-Identifier: Apache-2.0
"""Generated from mlx-vlm; regenerate with generate_backport.py."""

SOURCE_REVISION = "9a200804c81b98fd420d1f8a064a6824cec76f4f"
BASE_REVISION = "4f4634bb813c0298cb1467bed2e957526c71d0b4"
BACKPORTS = {'mlx_vlm.models.qwen_image.config': ('f223a1cd7ae83fa66ec090b0ee7512fd06e789512b8d5e3f2ff0d9dea47f2b26',
                                      '0099f6d10dcf9506b53d21aebd760c123a2d53ea7412da413d8ae74e0d90255e',
                                      (('from __future__ import annotations\n'
                                        '\n'
                                        'import json\n'
                                        'from dataclasses import dataclass\n'
                                        'from pathlib import Path\n'
                                        '\n'
                                        '\n',
                                        'from __future__ import annotations\n'
                                        '\n'
                                        'import json\n'
                                        'import math\n'
                                        'from collections.abc import Sequence\n'
                                        'from dataclasses import dataclass, replace\n'
                                        'from numbers import Real\n'
                                        'from pathlib import Path\n'
                                        '\n'
                                        '\n'),
                                       ('        uses_reference_kv_cache=True,\n'
                                        '    ),\n'
                                        '}\n'
                                        '\n'
                                        '_ALIASES = {\n'
                                        '    alias.lower(): variant for variant in '
                                        'VARIANTS.values() for alias in variant.aliases\n',
                                        '        uses_reference_kv_cache=True,\n'
                                        '    ),\n'
                                        '}\n'
                                        'VARIANTS["qwen-image-2.1-turbo"] = replace(\n'
                                        '    VARIANTS["qwen-image-2.1"],\n'
                                        '    name="qwen-image-2.1-turbo",\n'
                                        '    aliases=(\n'
                                        '        "qwen-image-2.1-turbo",\n'
                                        '        "qwen-image-2_1-turbo",\n'
                                        '        "qwen_image_2_1_turbo",\n'
                                        '        "Qwen/Qwen-Image-2.1-Turbo",\n'
                                        '    ),\n'
                                        '    repo_id="Qwen/Qwen-Image-2.1-Turbo",\n'
                                        '    local_dir_name="Qwen-Image-2.1-Turbo",\n'
                                        ')\n'
                                        '\n'
                                        '_ALIASES = {\n'
                                        '    alias.lower(): variant for variant in '
                                        'VARIANTS.values() for alias in variant.aliases\n'),
                                       ('    if root.parent.name == "snapshots" and '
                                        'root.parent.parent.name.startswith(\n'
                                        '        "models--"\n'
                                        '    ):\n'
                                        '        name = '
                                        'root.parent.parent.name.removeprefix("models--").replace("--", '
                                        '"/")\n'
                                        '    if "qwen" in name and "image" in name:\n'
                                        '        return VARIANTS["qwen-image-2.1"]\n'
                                        '\n'
                                        '    transformer_config = root / "transformer" / '
                                        '"config.json"\n'
                                        '    if transformer_config.exists():\n',
                                        '    if root.parent.name == "snapshots" and '
                                        'root.parent.parent.name.startswith(\n'
                                        '        "models--"\n'
                                        '    ):\n'
                                        '        name = (\n'
                                        '            '
                                        'root.parent.parent.name.removeprefix("models--").replace("--", '
                                        '"/").lower()\n'
                                        '        )\n'
                                        '    if "qwen" in name and "image" in name:\n'
                                        '        return VARIANTS["qwen-image-2.1-turbo" if "turbo" '
                                        'in name else "qwen-image-2.1"]\n'
                                        '\n'
                                        '    transformer_config = root / "transformer" / '
                                        '"config.json"\n'
                                        '    if transformer_config.exists():\n'),
                                       ('    return tuple(VARIANTS)\n'
                                        '\n'
                                        '\n'
                                        'def validate_dimensions(*, width: int, height: int) -> '
                                        'None:\n'
                                        '    for label, value in (("width", width), ("height", '
                                        'height)):\n'
                                        '        if value < 256 or value > 2048:\n',
                                        '    return tuple(VARIANTS)\n'
                                        '\n'
                                        '\n'
                                        'def validate_sigmas(sigmas: Sequence[float]) -> '
                                        'tuple[float, ...]:\n'
                                        '    if not isinstance(sigmas, Sequence) or not sigmas:\n'
                                        '        raise ValueError(\n'
                                        '            "sigmas must be a nonempty sequence excluding '
                                        'the terminal zero"\n'
                                        '        )\n'
                                        '    if any(\n'
                                        '        isinstance(value, bool)\n'
                                        '        or not isinstance(value, Real)\n'
                                        '        or not math.isfinite(value)\n'
                                        '        or not 0 < value <= 1\n'
                                        '        for value in sigmas\n'
                                        '    ):\n'
                                        '        raise ValueError("sigmas must contain finite '
                                        'numbers in (0, 1]")\n'
                                        '    values = tuple(float(value) for value in sigmas)\n'
                                        '    if any(a <= b for a, b in zip(values, values[1:])):\n'
                                        '        raise ValueError("sigmas must be strictly '
                                        'decreasing")\n'
                                        '    return values\n'
                                        '\n'
                                        '\n'
                                        'def load_sample_sigmas(model_path: str | Path) -> '
                                        'tuple[float, ...] | None:\n'
                                        '    path = Path(model_path) / "model_index.json"\n'
                                        '    if not path.exists():\n'
                                        '        return None\n'
                                        '    config = json.loads(path.read_text())\n'
                                        '    if not isinstance(config, dict):\n'
                                        '        raise ValueError(f"Expected an object in '
                                        '{path}")\n'
                                        '    sigmas = config.get("sample_sigmas")\n'
                                        '    return None if sigmas is None else '
                                        'validate_sigmas(sigmas)\n'
                                        '\n'
                                        '\n'
                                        'def resolve_sampling(\n'
                                        '    steps: int,\n'
                                        '    sigmas: Sequence[float] | None,\n'
                                        '    sample_sigmas: tuple[float, ...] | None,\n'
                                        ') -> tuple[int, tuple[float, ...] | None]:\n'
                                        '    if isinstance(steps, bool) or not isinstance(steps, '
                                        'int) or steps < 1:\n'
                                        '        raise ValueError("steps must be a positive '
                                        'integer")\n'
                                        '    selected = sample_sigmas if sigmas is None else '
                                        'sigmas\n'
                                        '    selected = None if selected is None else '
                                        'validate_sigmas(selected)\n'
                                        '    return (steps if selected is None else '
                                        'len(selected)), selected\n'
                                        '\n'
                                        '\n'
                                        'def validate_guidance(guidance: float) -> None:\n'
                                        '    if (\n'
                                        '        isinstance(guidance, bool)\n'
                                        '        or not isinstance(guidance, Real)\n'
                                        '        or not math.isfinite(guidance)\n'
                                        '        or guidance <= 0\n'
                                        '    ):\n'
                                        '        raise ValueError("guidance must be finite and '
                                        'positive")\n'
                                        '\n'
                                        '\n'
                                        'def validate_dimensions(*, width: int, height: int) -> '
                                        'None:\n'
                                        '    for label, value in (("width", width), ("height", '
                                        'height)):\n'
                                        '        if value < 256 or value > 2048:\n'))),
 'mlx_vlm.models.qwen_image.scheduler': ('2a8e6017536d8c6f5b9252d82fd2949de13e576a49735fa69926f410a12dea3b',
                               '80f6f6976f2ffa5f8b221bc7b28bdd0834ddb645e192649582af593a96a57875',
                                         (('"""FlowMatchEuler scheduler for Qwen-Image-2.1 '
                                           '(dynamic exponential shift).\n'
                                           '\n'
                                           'Mirrors the structure of ``flux2.scheduler`` but uses '
                                           "Qwen-Image's linear\n"
                                           '``calculate_shift`` (base/max shift over image '
                                           'sequence length) instead of\n',
                                           '"""FlowMatchEuler scheduler for Qwen-Image-2.1 and '
                                           'saved sampling grids.\n'
                                           '\n'
                                           'Mirrors the structure of ``flux2.scheduler`` but uses '
                                           "Qwen-Image's linear\n"
                                           '``calculate_shift`` (base/max shift over image '
                                           'sequence length) instead of\n'),
                                          ('\n'
                                           'from __future__ import annotations\n'
                                           '\n'
                                           'import mlx.core as mx\n'
                                           '\n'
                                           '\n'
                                           'def calculate_shift(\n',
                                           '\n'
                                           'from __future__ import annotations\n'
                                           '\n'
                                           'import math\n'
                                           'from collections.abc import Sequence\n'
                                           'from numbers import Real\n'
                                           '\n'
                                           'import mlx.core as mx\n'
                                           '\n'
                                           'from .config import resolve_sampling\n'
                                           '\n'
                                           '\n'
                                           'def calculate_shift(\n'),
                                          ('        max_image_seq_len: int = 8192,\n'
                                           '        num_train_timesteps: int = 1000,\n'
                                           '        shift_terminal: float | None = 0.02,\n'
                                           '    ) -> None:\n'
                                           '        sigmas = mx.linspace(\n'
                                           '            1.0, 1.0 / num_inference_steps, '
                                           'num_inference_steps, dtype=mx.float32\n'
                                           '        )\n'
                                           '        mu = calculate_shift(\n'
                                           '            image_seq_len, base_image_seq_len, '
                                           'max_image_seq_len, base_shift, max_shift\n'
                                           '        )\n'
                                           '        sigmas = mx.exp(mu) / (mx.exp(mu) + (1.0 / '
                                           'sigmas - 1.0))\n'
                                           '        # Stretch the shifted schedule before '
                                           'appending the final zero sigma.\n'
                                           '        # A one-step schedule has no interval to '
                                           'stretch and starts at pure noise.\n'
                                           '        if shift_terminal and num_inference_steps > '
                                           '1:\n'
                                           '            one_minus_sigmas = 1.0 - sigmas\n'
                                           '            scale = one_minus_sigmas[-1] / (1.0 - '
                                           'shift_terminal)\n'
                                           '            sigmas = 1.0 - one_minus_sigmas / scale\n'
                                           '        self.timesteps = sigmas * num_train_timesteps\n'
                                           '        self.sigmas = mx.concatenate(\n'
                                           '            [sigmas, mx.zeros((1,), '
                                           'dtype=sigmas.dtype)], axis=0\n',
                                           '        max_image_seq_len: int = 8192,\n'
                                           '        num_train_timesteps: int = 1000,\n'
                                           '        shift_terminal: float | None = 0.02,\n'
                                           '        sigmas: Sequence[float] | None = None,\n'
                                           '        use_dynamic_shifting: bool = True,\n'
                                           '        shift: float = 1.0,\n'
                                           '    ) -> None:\n'
                                           '        num_inference_steps, sigmas = '
                                           'resolve_sampling(\n'
                                           '            num_inference_steps, sigmas, None\n'
                                           '        )\n'
                                           '        if not isinstance(use_dynamic_shifting, '
                                           'bool):\n'
                                           '            raise ValueError("use_dynamic_shifting '
                                           'must be a boolean")\n'
                                           '        if (\n'
                                           '            isinstance(shift, bool)\n'
                                           '            or not isinstance(shift, Real)\n'
                                           '            or not math.isfinite(shift)\n'
                                           '            or shift <= 0\n'
                                           '        ):\n'
                                           '            raise ValueError("shift must be finite and '
                                           'positive")\n'
                                           '        if shift_terminal is not None and (\n'
                                           '            isinstance(shift_terminal, bool)\n'
                                           '            or not isinstance(shift_terminal, Real)\n'
                                           '            or not math.isfinite(shift_terminal)\n'
                                           '            or not 0 <= shift_terminal < 1\n'
                                           '        ):\n'
                                           '            raise ValueError("shift_terminal must be '
                                           'finite and in [0, 1)")\n'
                                           '        sigmas = (\n'
                                           '            mx.linspace(\n'
                                           '                1.0, 1.0 / num_inference_steps, '
                                           'num_inference_steps, dtype=mx.float32\n'
                                           '            )\n'
                                           '            if sigmas is None\n'
                                           '            else mx.array(sigmas, dtype=mx.float32)\n'
                                           '        )\n'
                                           '        if bool(mx.any(sigmas <= 0)) or '
                                           'bool(mx.any(sigmas[:-1] <= sigmas[1:])):\n'
                                           '            raise ValueError(\n'
                                           '                "sigmas must remain positive and '
                                           'strictly decreasing in float32"\n'
                                           '            )\n'
                                           '        if use_dynamic_shifting:\n'
                                           '            mu = calculate_shift(\n'
                                           '                image_seq_len,\n'
                                           '                base_image_seq_len,\n'
                                           '                max_image_seq_len,\n'
                                           '                base_shift,\n'
                                           '                max_shift,\n'
                                           '            )\n'
                                           '            sigmas = mx.exp(mu) / (mx.exp(mu) + (1.0 / '
                                           'sigmas - 1.0))\n'
                                           '        elif shift != 1.0:\n'
                                           '            sigmas = shift * sigmas / (1.0 + (shift - '
                                           '1.0) * sigmas)\n'
                                           '        # Stretch the shifted schedule before '
                                           'appending the final zero sigma.\n'
                                           '        # A one-step schedule has no interval to '
                                           'stretch and starts at pure noise.\n'
                                           '        if shift_terminal and num_inference_steps > '
                                           '1:\n'
                                           '            if float(sigmas[-1]) == 1.0:\n'
                                           '                raise ValueError("Cannot stretch a '
                                           'schedule whose last sigma is 1")\n'
                                           '            one_minus_sigmas = 1.0 - sigmas\n'
                                           '            scale = one_minus_sigmas[-1] / (1.0 - '
                                           'shift_terminal)\n'
                                           '            sigmas = 1.0 - one_minus_sigmas / scale\n'
                                           '        if (\n'
                                           '            not bool(mx.all(mx.isfinite(sigmas)))\n'
                                           '            or bool(mx.any(sigmas <= 0))\n'
                                           '            or bool(mx.any(sigmas[:-1] <= '
                                           'sigmas[1:]))\n'
                                           '        ):\n'
                                           '            raise ValueError("Processed sigmas must be '
                                           'finite, positive and decreasing")\n'
                                           '        self.timesteps = sigmas * num_train_timesteps\n'
                                           '        self.sigmas = mx.concatenate(\n'
                                           '            [sigmas, mx.zeros((1,), '
                                           'dtype=sigmas.dtype)], axis=0\n'))),
 'mlx_vlm.models.qwen_image.text_encoder': ('844c0f95932fdb28265f3ce25e17a5300802f5143ec593baf2ddcae0f8891115',
                                  'edfdfe05f14b5c3a9bad9a2ca0cf26c885753ae5732c194e50355d47f001500f',
                                            (('        return hidden[:, self.drop_idx :]\n'
                                              '\n'
                                              '    @property\n'
                                              '    def processor(self):\n'
                                              '        if self._processor is None:\n'
                                              '            config = json.loads(\n'
                                              '                (Path(self.processor_dir) / '
                                              '"preprocessor_config.json").read_text()\n'
                                              '            )\n'
                                              '            size = config.get("size", {})\n'
                                              '            config["min_pixels"] = '
                                              'config.get("min_pixels") or size.get(\n'
                                              '                "shortest_edge", 65536\n'
                                              '            )\n',
                                              '        return hidden[:, self.drop_idx :]\n'
                                              '\n'
                                              '    @property\n'
                                              '    def processor(self) -> Qwen3VLProcessor:\n'
                                              '        if self._processor is None:\n'
                                              '            path = Path(self.processor_dir) / '
                                              '"preprocessor_config.json"\n'
                                              '            if path.exists():\n'
                                              '                config = '
                                              'json.loads(path.read_text())\n'
                                              '            else:\n'
                                              '                path = Path(self.processor_dir) / '
                                              '"processor_config.json"\n'
                                              '                config = '
                                              'json.loads(path.read_text())\n'
                                              '                if not isinstance(config, dict) or '
                                              '"image_processor" not in config:\n'
                                              '                    raise ValueError(f"Missing '
                                              'image_processor configuration in {path}")\n'
                                              '                config = config["image_processor"]\n'
                                              '            if not isinstance(config, dict):\n'
                                              '                raise ValueError(\n'
                                              '                    f"Expected image processor '
                                              'configuration object in {path}"\n'
                                              '                )\n'
                                              '            size = config.get("size", {})\n'
                                              '            if not isinstance(size, dict):\n'
                                              '                raise ValueError(f"Expected image '
                                              'processor size object in {path}")\n'
                                              '            config["min_pixels"] = '
                                              'config.get("min_pixels") or size.get(\n'
                                              '                "shortest_edge", 65536\n'
                                              '            )\n'),)),
 'mlx_vlm.models.qwen_image.pipeline': ('10d29a321c9467b571e284c56167e4e666f7441bb66d43c03c1c3649debc6280',
                              '2fb6b85468f0ff8bf58b5f8cdbb2381b788ece4f19a4495b386fed99f75e112b',
                                        (('import numpy as np\n'
                                          'from PIL import Image\n'
                                          '\n'
                                          'from .config import QwenImageVariant, get_variant\n'
                                          'from .download import download_model, '
                                          'validate_model_layout\n'
                                          'from .kv_cache import QwenImageKVCache\n'
                                          'from .scheduler import '
                                          'FlowMatchEulerDiscreteScheduler\n',
                                          'import numpy as np\n'
                                          'from PIL import Image\n'
                                          '\n'
                                          'from .config import (\n'
                                          '    QwenImageVariant,\n'
                                          '    get_variant,\n'
                                          '    load_sample_sigmas,\n'
                                          '    resolve_sampling,\n'
                                          '    validate_guidance,\n'
                                          ')\n'
                                          'from .download import download_model, '
                                          'validate_model_layout\n'
                                          'from .kv_cache import QwenImageKVCache\n'
                                          'from .scheduler import '
                                          'FlowMatchEulerDiscreteScheduler\n'),
                                         ('        )\n'
                                          '        self.latents_std = '
                                          'mx.array(cfg["latents_std"]).reshape(1, self.z_dim, 1, '
                                          '1, 1)\n'
                                          '        self.quantization_config = '
                                          '_read_quant(self.model_path / "transformer")\n'
                                          '        scheduler_path = self.model_path / "scheduler" '
                                          '/ "scheduler_config.json"\n'
                                          '        scheduler_config = (\n'
                                          '            json.loads(scheduler_path.read_text()) if '
                                          'scheduler_path.exists() else {}\n'
                                          '        )\n'
                                          '        self.scheduler_config = {\n'
                                          '            key: scheduler_config[key]\n'
                                          '            for key in (\n',
                                          '        )\n'
                                          '        self.latents_std = '
                                          'mx.array(cfg["latents_std"]).reshape(1, self.z_dim, 1, '
                                          '1, 1)\n'
                                          '        self.quantization_config = '
                                          '_read_quant(self.model_path / "transformer")\n'
                                          '        self.sample_sigmas = '
                                          'load_sample_sigmas(self.model_path)\n'
                                          '        scheduler_path = self.model_path / "scheduler" '
                                          '/ "scheduler_config.json"\n'
                                          '        scheduler_config = (\n'
                                          '            json.loads(scheduler_path.read_text()) if '
                                          'scheduler_path.exists() else {}\n'
                                          '        )\n'
                                          '        if not isinstance(scheduler_config, dict):\n'
                                          '            raise ValueError(f"Expected an object in '
                                          '{scheduler_path}")\n'
                                          '        for key in (\n'
                                          '            "use_beta_sigmas",\n'
                                          '            "use_exponential_sigmas",\n'
                                          '            "use_karras_sigmas",\n'
                                          '            "invert_sigmas",\n'
                                          '            "stochastic_sampling",\n'
                                          '        ):\n'
                                          '            if scheduler_config.get(key, False) is not '
                                          'False:\n'
                                          '                raise ValueError(f"Unsupported '
                                          'Qwen-Image scheduler setting: {key}")\n'
                                          '        if scheduler_config.get("time_shift_type", '
                                          '"exponential") != "exponential":\n'
                                          '            raise ValueError("Qwen-Image only supports '
                                          'exponential time shifting")\n'
                                          '        self.scheduler_config = {\n'
                                          '            key: scheduler_config[key]\n'
                                          '            for key in (\n'),
                                         ('                "max_image_seq_len",\n'
                                          '                "num_train_timesteps",\n'
                                          '                "shift_terminal",\n'
                                          '            )\n'
                                          '            if key in scheduler_config\n'
                                          '        }\n',
                                          '                "max_image_seq_len",\n'
                                          '                "num_train_timesteps",\n'
                                          '                "shift_terminal",\n'
                                          '                "use_dynamic_shifting",\n'
                                          '                "shift",\n'
                                          '            )\n'
                                          '            if key in scheduler_config\n'
                                          '        }\n'),
                                         ('        guidance: float = 1.0,\n'
                                          '        negative_prompt: str = " ",\n'
                                          '        num_images: int = 1,\n'
                                          '    ) -> mx.array:\n'
                                          '        """Generate one ``[H, W, 3]`` image, or ``[N, '
                                          'H, W, 3]`` when num_images > 1."""\n'
                                          '        emb = '
                                          'self.text_encoder.encode(prompt).astype(mx.bfloat16)\n'
                                          '        do_cfg = guidance is not None and guidance > '
                                          '1.0\n'
                                          '        neg = (\n',
                                          '        guidance: float = 1.0,\n'
                                          '        negative_prompt: str = " ",\n'
                                          '        num_images: int = 1,\n'
                                          '        sigmas: Sequence[float] | None = None,\n'
                                          '    ) -> mx.array:\n'
                                          '        """Generate one ``[H, W, 3]`` image, or ``[N, '
                                          'H, W, 3]`` when num_images > 1."""\n'
                                          '        steps, sigmas = resolve_sampling(steps, sigmas, '
                                          'self.sample_sigmas)\n'
                                          '        validate_guidance(guidance)\n'
                                          '        emb = '
                                          'self.text_encoder.encode(prompt).astype(mx.bfloat16)\n'
                                          '        do_cfg = guidance is not None and guidance > '
                                          '1.0\n'
                                          '        neg = (\n'),
                                         ('            height=height,\n'
                                          '            guidance=guidance,\n'
                                          '            num_images=num_images,\n'
                                          '        )[..., :3]\n'
                                          '\n'
                                          '    def edit_array(\n',
                                          '            height=height,\n'
                                          '            guidance=guidance,\n'
                                          '            num_images=num_images,\n'
                                          '            sigmas=sigmas,\n'
                                          '        )[..., :3]\n'
                                          '\n'
                                          '    def edit_array(\n'),
                                         ('        negative_prompt: str = " ",\n'
                                          '        output_resolution: int = 1024,\n'
                                          '        use_kv_cache: bool = True,\n'
                                          '    ) -> mx.array:\n'
                                          '        """Edit one or more references; return an [H, '
                                          'W, 4] uint8 RGBA image."""\n'
                                          '        if not image_paths:\n'
                                          '            raise ValueError("At least one reference '
                                          'image is required")\n'
                                          '        if output_resolution < 256:\n',
                                          '        negative_prompt: str = " ",\n'
                                          '        output_resolution: int = 1024,\n'
                                          '        use_kv_cache: bool = True,\n'
                                          '        sigmas: Sequence[float] | None = None,\n'
                                          '    ) -> mx.array:\n'
                                          '        """Edit one or more references; return an [H, '
                                          'W, 4] uint8 RGBA image."""\n'
                                          '        steps, sigmas = resolve_sampling(steps, sigmas, '
                                          'self.sample_sigmas)\n'
                                          '        validate_guidance(guidance)\n'
                                          '        if not image_paths:\n'
                                          '            raise ValueError("At least one reference '
                                          'image is required")\n'
                                          '        if output_resolution < 256:\n'),
                                         ('            image_pad_mask=image_pad_mask,\n'
                                          '            '
                                          'negative_image_pad_mask=negative_image_pad_mask,\n'
                                          '            use_kv_cache=use_kv_cache,\n'
                                          '        )\n'
                                          '\n'
                                          '    def _sample(\n',
                                          '            image_pad_mask=image_pad_mask,\n'
                                          '            '
                                          'negative_image_pad_mask=negative_image_pad_mask,\n'
                                          '            use_kv_cache=use_kv_cache,\n'
                                          '            sigmas=sigmas,\n'
                                          '        )\n'
                                          '\n'
                                          '    def _sample(\n'),
                                         ('        image_pad_mask=None,\n'
                                          '        negative_image_pad_mask=None,\n'
                                          '        use_kv_cache=False,\n'
                                          '    ) -> mx.array:\n'
                                          '        z = self.z_dim\n'
                                          '        h_lat, w_lat = height // 16, width // 16\n'
                                          '        tokens = h_lat * w_lat\n',
                                          '        image_pad_mask=None,\n'
                                          '        negative_image_pad_mask=None,\n'
                                          '        use_kv_cache=False,\n'
                                          '        sigmas=None,\n'
                                          '    ) -> mx.array:\n'
                                          '        steps, sigmas = resolve_sampling(steps, sigmas, '
                                          'self.sample_sigmas)\n'
                                          '        z = self.z_dim\n'
                                          '        h_lat, w_lat = height // 16, width // 16\n'
                                          '        tokens = h_lat * w_lat\n'),
                                         ('            if neg is not None:\n'
                                          '                neg = mx.broadcast_to(neg, (num_images, '
                                          '*neg.shape[1:]))\n'
                                          '        scheduler = FlowMatchEulerDiscreteScheduler(\n'
                                          '            image_seq_len=tokens, '
                                          'num_inference_steps=steps, **self.scheduler_config\n'
                                          '        )\n'
                                          '        cache = negative_cache = None\n'
                                          '        if (\n',
                                          '            if neg is not None:\n'
                                          '                neg = mx.broadcast_to(neg, (num_images, '
                                          '*neg.shape[1:]))\n'
                                          '        scheduler = FlowMatchEulerDiscreteScheduler(\n'
                                          '            image_seq_len=tokens,\n'
                                          '            num_inference_steps=steps,\n'
                                          '            sigmas=sigmas,\n'
                                          '            **self.scheduler_config,\n'
                                          '        )\n'
                                          '        cache = negative_cache = None\n'
                                          '        if (\n'),
                                         ('            cache = QwenImageKVCache(num_layers)\n'
                                          '            if neg is not None:\n'
                                          '                negative_cache = '
                                          'QwenImageKVCache(num_layers)\n'
                                          '        for i in range(steps):\n'
                                          '            t = scheduler.timesteps[i : i + '
                                          '1].astype(latents.dtype) / 1000\n'
                                          '            model_input = latents\n'
                                          '            edit_kwargs = {}\n',
                                          '            cache = QwenImageKVCache(num_layers)\n'
                                          '            if neg is not None:\n'
                                          '                negative_cache = '
                                          'QwenImageKVCache(num_layers)\n'
                                          '        for i in range(len(scheduler.timesteps)):\n'
                                          '            t = scheduler.timesteps[i : i + '
                                          '1].astype(latents.dtype) / 1000\n'
                                          '            model_input = latents\n'
                                          '            edit_kwargs = {}\n'))),
 'mlx_vlm.models.qwen_image.model': ('c3cc0c52908879d46d577a75787662e0eb30dd8a513a3a8e96b19c7dbd236f1f',
                           'aa6a434676e00ace2b6fbcb28505aab0b5b67a82ce5c49c94d20e618eea841d7',
                                     (('from __future__ import annotations\n'
                                       '\n'
                                       'from dataclasses import dataclass\n'
                                       'from pathlib import Path\n'
                                       'from typing import Any, ClassVar\n'
                                       '\n',
                                       'from __future__ import annotations\n'
                                       '\n'
                                       'from dataclasses import dataclass, field\n'
                                       'from pathlib import Path\n'
                                       'from typing import Any, ClassVar\n'
                                       '\n'),
                                      ('    ImageGenerationRequest,\n'
                                       '    ImageGenerationResult,\n'
                                       ')\n'
                                       'from mlx_vlm.generate.image_defaults import '
                                       'ImageSamplingDefaults\n'
                                       '\n'
                                       'from .config import QwenImageVariant, get_variant, '
                                       'variant_from_local_path\n'
                                       'from .download import validate_model_layout\n'
                                       'from .pipeline import QwenImagePipeline\n'
                                       '\n',
                                       '    ImageGenerationRequest,\n'
                                       '    ImageGenerationResult,\n'
                                       ')\n'
                                       'from mlx_vlm.generate.image_defaults import '
                                       'ImageSamplingDefaults, image_metadata_path\n'
                                       '\n'
                                       'from .config import (\n'
                                       '    QwenImageVariant,\n'
                                       '    get_variant,\n'
                                       '    load_sample_sigmas,\n'
                                       '    resolve_sampling,\n'
                                       '    validate_guidance,\n'
                                       '    variant_from_local_path,\n'
                                       ')\n'
                                       'from .download import validate_model_layout\n'
                                       'from .pipeline import QwenImagePipeline\n'
                                       '\n'),
                                      ('    model_id: str\n'
                                       '    family: str = "qwen_image"\n'
                                       '\n'
                                       '    default_sampling: ClassVar[ImageSamplingDefaults] = '
                                       'ImageSamplingDefaults(30, 1.0)\n'
                                       '\n'
                                       '    @classmethod\n'
                                       '    def resolve_defaults(\n'
                                       '        cls, model: str, *, model_path: Path | None = '
                                       'None\n'
                                       '    ) -> ImageSamplingDefaults:\n'
                                       '        return cls.default_sampling\n'
                                       '\n'
                                       '    @property\n'
                                       '    def variant(self) -> str:\n',
                                       '    model_id: str\n'
                                       '    family: str = "qwen_image"\n'
                                       '\n'
                                       '    _default_sampling: ClassVar[ImageSamplingDefaults] = '
                                       'ImageSamplingDefaults(30, 1.0)\n'
                                       '    default_sampling: ImageSamplingDefaults = '
                                       'field(init=False)\n'
                                       '\n'
                                       '    def __post_init__(self) -> None:\n'
                                       '        saved = self.pipeline.sample_sigmas\n'
                                       '        self.default_sampling = ImageSamplingDefaults(\n'
                                       '            self._default_sampling.steps if saved is None '
                                       'else len(saved),\n'
                                       '            self._default_sampling.guidance,\n'
                                       '        )\n'
                                       '\n'
                                       '    @classmethod\n'
                                       '    def resolve_defaults(\n'
                                       '        cls, model: str, *, model_path: Path | None = '
                                       'None\n'
                                       '    ) -> ImageSamplingDefaults:\n'
                                       '        if model_path is None:\n'
                                       '            root = Path(model).expanduser()\n'
                                       '            if root.is_dir():\n'
                                       '                model_path = root\n'
                                       '            else:\n'
                                       '                variant = resolve_variant(model)\n'
                                       '                if variant.name != '
                                       '"qwen-image-2.1-turbo":\n'
                                       '                    return cls._default_sampling\n'
                                       '                model_path = '
                                       'image_metadata_path(variant.repo_id)\n'
                                       '        saved = load_sample_sigmas(model_path)\n'
                                       '        return ImageSamplingDefaults(\n'
                                       '            cls._default_sampling.steps if saved is None '
                                       'else len(saved),\n'
                                       '            cls._default_sampling.guidance,\n'
                                       '        )\n'
                                       '\n'
                                       '    @property\n'
                                       '    def variant(self) -> str:\n'),
                                      ('        seed = 0 if request.seed is None else '
                                       'request.seed\n'
                                       '        defaults = self.default_sampling\n'
                                       '        steps = request.resolve_steps(defaults.steps)\n'
                                       '        guidance = '
                                       'request.resolve_guidance(defaults.guidance)\n'
                                       '        array = self.pipeline.generate_array(\n'
                                       '            request.prompt,\n'
                                       '            seed=seed,\n',
                                       '        seed = 0 if request.seed is None else '
                                       'request.seed\n'
                                       '        defaults = self.default_sampling\n'
                                       '        steps = request.resolve_steps(defaults.steps)\n'
                                       '        steps, sigmas = resolve_sampling(\n'
                                       '            steps, request.extra.get("sigmas"), '
                                       'self.pipeline.sample_sigmas\n'
                                       '        )\n'
                                       '        guidance = '
                                       'request.resolve_guidance(defaults.guidance)\n'
                                       '        validate_guidance(guidance)\n'
                                       '        array = self.pipeline.generate_array(\n'
                                       '            request.prompt,\n'
                                       '            seed=seed,\n'),
                                      ('            guidance=guidance,\n'
                                       '            '
                                       'negative_prompt=request.extra.get("negative_prompt", " '
                                       '"),\n'
                                       '            num_images=int(request.extra.get("num_images", '
                                       '1)),\n'
                                       '        )\n'
                                       '        metadata = {"model_path": '
                                       'str(self.pipeline.model_path)}\n'
                                       '        if self.pipeline.quantization_config:\n',
                                       '            guidance=guidance,\n'
                                       '            '
                                       'negative_prompt=request.extra.get("negative_prompt", " '
                                       '"),\n'
                                       '            num_images=int(request.extra.get("num_images", '
                                       '1)),\n'
                                       '            sigmas=sigmas,\n'
                                       '        )\n'
                                       '        metadata = {"model_path": '
                                       'str(self.pipeline.model_path)}\n'
                                       '        if self.pipeline.quantization_config:\n'),
                                      ('    is_image_generation_model: ClassVar[bool] = False\n'
                                       '    is_image_edit_model: ClassVar[bool] = True\n'
                                       '\n'
                                       '    default_sampling: ClassVar[ImageSamplingDefaults] = '
                                       'ImageSamplingDefaults(40, 1.0)\n'
                                       '\n'
                                       '    @classmethod\n'
                                       '    def resolve_defaults(\n'
                                       '        cls, model: str, *, model_path: Path | None = '
                                       'None\n'
                                       '    ) -> ImageSamplingDefaults:\n'
                                       '        return cls.default_sampling\n'
                                       '\n'
                                       '    def edit(self, request: ImageEditRequest) -> '
                                       'ImageGenerationResult:\n'
                                       '        seed = 0 if request.seed is None else '
                                       'request.seed\n'
                                       '        defaults = self.default_sampling\n'
                                       '        steps = request.resolve_steps(defaults.steps)\n'
                                       '        guidance = '
                                       'request.resolve_guidance(defaults.guidance)\n'
                                       '        array = self.pipeline.edit_array(\n'
                                       '            request.prompt,\n'
                                       '            request.image_paths,\n',
                                       '    is_image_generation_model: ClassVar[bool] = False\n'
                                       '    is_image_edit_model: ClassVar[bool] = True\n'
                                       '\n'
                                       '    _default_sampling: ClassVar[ImageSamplingDefaults] = '
                                       'ImageSamplingDefaults(40, 1.0)\n'
                                       '\n'
                                       '    def edit(self, request: ImageEditRequest) -> '
                                       'ImageGenerationResult:\n'
                                       '        seed = 0 if request.seed is None else '
                                       'request.seed\n'
                                       '        defaults = self.default_sampling\n'
                                       '        steps = request.resolve_steps(defaults.steps)\n'
                                       '        steps, sigmas = resolve_sampling(\n'
                                       '            steps, request.extra.get("sigmas"), '
                                       'self.pipeline.sample_sigmas\n'
                                       '        )\n'
                                       '        guidance = '
                                       'request.resolve_guidance(defaults.guidance)\n'
                                       '        validate_guidance(guidance)\n'
                                       '        array = self.pipeline.edit_array(\n'
                                       '            request.prompt,\n'
                                       '            request.image_paths,\n'),
                                      ('            '
                                       'negative_prompt=request.extra.get("negative_prompt", " '
                                       '"),\n'
                                       '            '
                                       'output_resolution=request.extra.get("output_resolution", '
                                       '1024),\n'
                                       '            use_kv_cache=request.extra.get("use_kv_cache", '
                                       'True),\n'
                                       '        )\n'
                                       '        metadata = {\n'
                                       '            "model_path": str(self.pipeline.model_path),\n',
                                       '            '
                                       'negative_prompt=request.extra.get("negative_prompt", " '
                                       '"),\n'
                                       '            '
                                       'output_resolution=request.extra.get("output_resolution", '
                                       '1024),\n'
                                       '            use_kv_cache=request.extra.get("use_kv_cache", '
                                       'True),\n'
                                       '            sigmas=sigmas,\n'
                                       '        )\n'
                                       '        metadata = {\n'
                                       '            "model_path": '
                                       'str(self.pipeline.model_path),\n'))),
 'mlx_vlm.generate.image': ('0c49d940b6d575d445d19c930a7b95e90de1291522fe6dcb9724805b7f117701',
                            '0cff132a99b7f740bd8116378514829e6d81d78b5ac54cd84d396d92ca4d0e37',
                            (('def _model_types_from_class_name(class_name: str) -> tuple[str, '
                              '...]:\n'
                              '    tokens = re.findall(r"[A-Z][a-z0-9]*|[A-Z]+(?=[A-Z]|$)", '
                              'class_name)\n'
                              '    candidates: list[str] = []\n'
                              '    for end in range(1, len(tokens) + 1):\n'
                              '        _add_model_type(candidates, "_".join(tokens[:end]))\n'
                              '        if end > 1:\n',
                              'def _model_types_from_class_name(class_name: str) -> tuple[str, '
                              '...]:\n'
                              '    tokens = re.findall(r"[A-Z][a-z0-9]*|[A-Z]+(?=[A-Z]|$)", '
                              'class_name)\n'
                              '    candidates: list[str] = []\n'
                              '    if class_name.startswith("QwenImage21"):\n'
                              '        _add_model_type(candidates, "qwen_image")\n'
                              '    for end in range(1, len(tokens) + 1):\n'
                              '        _add_model_type(candidates, "_".join(tokens[:end]))\n'
                              '        if end > 1:\n'),))}
